// Writes the ABIs the web app needs into web/src/abi.ts, so the site builds without compiling contracts.
// Run `npm run abi` after changing a contract; CI fails if the committed file is stale.
import { readFileSync, writeFileSync } from "node:fs";

const contracts = {
  pilotVaultAbi: "PilotVault.sol/PilotVault",
  pilotVaultFactoryAbi: "PilotVaultFactory.sol/PilotVaultFactory",
  pilotRegistryAbi: "PilotRegistry.sol/PilotRegistry",
  mockErc20Abi: "mocks/MockERC20.sol/MockERC20",
};
let out = "// Generated by scripts/export-abi.mjs from the compiled contracts. Do not edit.\n";
for (const [name, path] of Object.entries(contracts)) {
  const { abi } = JSON.parse(readFileSync(`artifacts/contracts/${path}.json`, "utf8"));
  out += `\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}
writeFileSync("web/src/abi.ts", out);
console.log("wrote web/src/abi.ts");
