// Generated by scripts/export-codeprints.mjs from this repository's build (solc 0.8.28). Do not edit.
import type { CodePrint } from "../../agent/codecheck";

export const SOLC_VERSION = "0.8.28";

export const CODE_PRINTS = {
  PilotVault: {
    hash: "0xb0dbe232bb86a86efccaacfd328954910edf3a0c8ca3c87022bb52b4a738619d",
    immutables: [[13190, 32], [13235, 32], [17951, 32], [17993, 32], [18035, 32], [18116, 32], [18156, 32]],
  },
  PilotVaultFactory: {
    hash: "0x6bacf5f864d2efb9c4b85926f4e13e25346e1ea71ea00f7af0fe19809e2bef71",
    immutables: [[94, 32], [363, 32]],
  },
  PilotRegistry: {
    hash: "0x82ff5919c4fb84527221338f4f81185f22c554b77777171d733629e132478c3c",
    immutables: [],
  },
  MandateCredential: {
    hash: "0x8a7d12282eae22b7ed066cea63b4cd299f169a44592b1b2ff43db5231dc0fcf6",
    immutables: [[594, 32], [647, 32], [1828, 32], [1892, 32], [4323, 32]],
  },
  PilotJournal: {
    hash: "0xa2219b7ae080a4f3560ab5d374c5a9687b7f0d2afc8d6180e9a2ef8734df3a60",
    immutables: [[657, 32]],
  },
  PilotFundFactory: {
    hash: "0x7f7d2f0dc59040980389cdf8d3d669fd523e70654cfa04f36740a18a2dcf3082",
    immutables: [[229, 32], [366, 32]],
  },
  PilotFund: {
    hash: "0x1b98d6681e84849b52fe45e8b372ee98d45cfce2c0f795feb0264cf03ce3c3fa",
    immutables: [[932, 32], [1879, 32], [2487, 32], [3285, 32], [3349, 32], [3536, 32], [3600, 32], [4054, 32], [4255, 32], [4823, 32], [4917, 32], [5708, 32], [5904, 32], [6379, 32], [6490, 32], [6687, 32], [6825, 32], [7823, 32], [7873, 32], [7917, 32], [8056, 32], [8894, 32], [9052, 32], [9661, 32], [9736, 32], [10286, 32], [10328, 32], [10370, 32], [10451, 32], [10491, 32]],
  },
} as const satisfies Record<string, CodePrint>;
